export type MethodCategory = "public-dataset" | "synthetic" | "open-method";

export interface MethodEntry {
  id: string;
  title: string;
  category: MethodCategory;
  source: string;
  description: string;
  url?: string;
}

export const CATEGORY_LABELS: Record<MethodCategory, string> = {
  "public-dataset": "Public dataset",
  synthetic: "Synthetic approximation",
  "open-method": "Open method",
};

/**
 * Documents where every number in DBO comes from. Grounded in
 * backend/data/*.json meta sources and data_pipeline/ builders — shown in
 * the /methods page to make the model auditable rather than a black box.
 */
export const METHOD_ENTRIES: MethodEntry[] = [
  {
    id: "location",
    title: "Location & county lookup",
    category: "public-dataset",
    source: "U.S. Census Bureau — 2020 ZCTA-to-county relationship file",
    description:
      "Every ZIP code is mapped to its county (and state) via the Census 2020 ZCTA20-to-county relationship file. The full crosswalk is generated once by an open script (data_pipeline/build_crosswalk.py); the committed demo subset covers the demo ZIPs.",
    url: "https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.2020.html",
  },
  {
    id: "climate-zones",
    title: "Climate zone groups",
    category: "public-dataset",
    source: "ASHRAE-style climate zone classification per weather station",
    description:
      "Locations are grouped into climate zone families (hot-humid, hot-dry, mixed-humid, mixed-dry/marine, very-cold/cold) following ASHRAE Standard 169 conventions. The group drives heating/cooling load shapes, heat-pump efficiency and solar yield.",
  },
  {
    id: "weather",
    title: "Weather & solar profiles (representative meteorological year)",
    category: "synthetic",
    source:
      "Deterministic physics-based approximation, generated by data_pipeline/build_tmy.py (seed 42)",
    description:
      "Hourly temperature and clear-sky irradiance for 8,760 hours are built from solar geometry plus seasonal/diurnal temperature anchors per station. Profiles are fully reproducible and transparent — but they approximate, not replace, real TMY3 records. Results should be read as directionally credible, not investment-grade.",
  },
  {
    id: "eui",
    title: "Energy use intensity benchmarks",
    category: "public-dataset",
    source: "CBECS 2018 survey medians (EIA Commercial Buildings Energy Consumption Survey)",
    description:
      "Baseline electricity and gas use per square foot start from CBECS 2018 medians per building type, adjusted approximately for climate zone and construction vintage.",
    url: "https://www.eia.gov/consumption/commercial/",
  },
  {
    id: "tariffs",
    title: "Energy tariffs & grid carbon intensity",
    category: "public-dataset",
    source: "EIA state average tariffs · eGRID2022 subregion averages",
    description:
      "Electricity price ($/kWh), demand charges ($/kW-month), gas price ($/therm) and grid emission factors (kgCO₂e/MWh) are state-level approximations from EIA average tariffs and EPA eGRID2022 subregion averages.",
    url: "https://www.epa.gov/egrid",
  },
  {
    id: "hazard",
    title: "Climate resilience hazard scores",
    category: "public-dataset",
    source: "FEMA National Risk Index (NRI), county level",
    description:
      "Expected-loss-derived scores for extreme heat, cold, flood, hurricane and wildfire come from FEMA NRI county data (built by data_pipeline/build_nri.py). When the NRI file cannot be fetched, an embedded state-level fallback is used and flagged honestly.",
    url: "https://hazards.fema.gov/nri/",
  },
  {
    id: "dispatch",
    title: "Asset dispatch optimization",
    category: "open-method",
    source: "Hourly linear program over all 8,760 hours",
    description:
      "Solar PV, battery storage and heat pumps are dispatched by a linear program that minimizes total annual energy cost subject to engineering constraints (state-of-charge limits, export credit fraction, peak thermal coverage). The optimizer evaluates candidate system sizes and reports the trace, so every recommendation can be inspected rather than trusted blindly.",
  },
  {
    id: "finance",
    title: "Financial comparison (CapEx vs Energy-as-a-Service)",
    category: "open-method",
    source: "Standard NPV / IRR / simple-payback cashflow model",
    description:
      "Direct CapEx is compared with a financed EaaS structure on customer net present value using standard discounted-cashflow arithmetic at a stated discount rate with published incentives applied. All rate assumptions are surfaced in-app (see Assumptions panel).",
  },
];

export const HONESTY_NOTE =
  "Load profiles and solar irradiance are deterministic synthetic approximations (" +
  '"representative meteorological year"); benchmarks are CBECS-derived medians; ' +
  "tariffs are state averages. Outputs are directionally credible, not investment-grade.";
